version: '3.8'

services:
  # Laravel App (PHP)
  laravel:
    build:
      context: ./docker/php
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5173:5173"

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  # MySQL Database
  db:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: laravel_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_AUTH_MECHANISM: SCRAM-SHA-1  # Force compatible authentication
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 3
      timeout: 5s

  # Redis for Caching
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # Node.js (Vue.js Build)
  node:
    image: node:latest
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["npm"]
    command: ["run", "dev"]
    depends_on:
      - laravel

volumes:
  mysql_data:
  mongodb_data:
